Import('listFiles')
Import('baseEnv')

env = baseEnv.Clone()

#  where to find external libraries
##env.AppendUnique(LIBPATH = [env['LIBDIR'], '/usr/lib64/mysql'])
env.AppendUnique(LIBPATH = [env['LIBDIR']])

# ..and what they're called
env.Append(LIBS = ['mysqlclient', 'yaml-cpp'])


ingest = env.Program('ingestTraveler', listFiles(['*.cxx', 'db/*.cxx']) )
ingestInstalled = env.Install(env['BINDIR'], ingest)
env.Alias('all', ingestInstalled)
env.Default(ingestInstalled)
