# -*- python -*-
import os.path   #, SCons,glob

def listFiles(files, **kw):
    allFiles = []
    for file in files:
        globFiles = Glob(file)
        newFiles = []
        for globFile in globFiles:
	    if 'recursive' in kw and kw.get('recursive') and os.path.isdir(globFile.srcnode().abspath) and os.path.basename(globFile.srcnode().abspath) != 'CVS':
	        allFiles+=listFiles([str(Dir('.').srcnode().rel_path(globFile.srcnode()))+"/*"], recursive = True)
	    if os.path.isfile(globFile.srcnode().abspath):
	        allFiles.append(globFile)
    return allFiles

Export('listFiles')

baseEnv = Environment()
# Dirs where things can be installed:
baseEnv['INCDIR'] = Dir('#include')
baseEnv['LIBDIR'] = Dir('#lib')
baseEnv['BINDIR'] = Dir('#bin')

# Externals: YAML under /usr/local
# Mysql in /usr/bin, /usr/lib, etc.
#  Include paths are 
#  among the standard ones, but just in case add /usr/local/include for YAML
baseEnv.AppendUnique(CPPPATH = ['#include', '/usr/local/include'])
baseEnv.AppendUnique(CCFLAGS = '-g')
baseEnv.SConsignFile("signatures/.sconsign.dblite")
Export('baseEnv')

#  Define targets
baseEnv.SConscript('yaml-cpp/SConscript', variant_dir=('yaml-cpp/build'), duplicate=0)
baseEnv.SConscript('src/SConscript', variant_dir=('src/build'), duplicate=0)
