# -*- python -*-
import os.path   #, SCons,glob

def listFiles(files, **kw):
    allFiles = []
    for file in files:
        globFiles = Glob(file)
        newFiles = []
        for globFile in globFiles:
	    if 'recursive' in kw and kw.get('recursive') and os.path.isdir(globFile.srcnode().abspath) and os.path.basename(globFile.srcnode().abspath) != 'CVS':
	        allFiles+=listFiles([str(Dir('.').srcnode().rel_path(globFile.srcnode()))+"/*"], recursive = True)
	    if os.path.isfile(globFile.srcnode().abspath):
	        allFiles.append(globFile)
    return allFiles

Export('listFiles')

baseEnv = Environment()
# Externals: YAML under /usr/local
# Mysql in /usr/bin, /usr/lib, etc.
#  Include paths are 
#  among the standard ones, but just in case add /usr/local/include for YAML
baseEnv.AppendUnique(CPPPATH = ['#include', '/usr/local/include'])
baseEnv.AppendUnique(CCFLAGS = '-g')
#  where to find external libraries
baseEnv.AppendUnique(LIBPATH = ['/usr/local/lib', '/usr/lib64/mysql'])
# ..and what they're called
baseEnv.Append(LIBS = ['mysqlclient', 'yaml-cpp'])
baseEnv.SConsignFile("signatures/.sconsign.dblite")
Export('baseEnv')

#  Define targets
baseEnv.SConscript('src/SConscript', variant_dir=('build'), duplicate=0)
